trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'sp-ado'
  resourceGroupName: 'rg-ado-created'
  location: 'westeurope'
  templateFile: 'main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az deployment sub create --name "Test ADI Bicep" --template-file "main.bicep" --parameters location=$(location) rgName=$(resourcegroupName)