trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'windows-latest'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'sp-ado'
    ScriptType: inlineScript
    Inline: |
      Get-Module -ListAvailable
