trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'windows-latest'

pool:
  vmImage: $(vmImageName)

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: | 
      $host = $env:HOSTNAME
      Write-hot $host