trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'sp-ado'
  resourceGroupName: 'rg-ado-created001'
  location: 'westeurope'
  templateFile: 'main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  name: 'InstallBicep'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az bicep install
      bicepVersion=`az bicep version -o tsv`
      echo $bicepVersion
      echo "##vso[task.setvariable variable=bicepVersion;]$bicepVersion"
      rgCreation=`az deployment sub create --location $(location) --template-file $(templateFile) --parameters location=$(location) rgName=$(resourceGroupName) -o tsv --query '[].[location]'`
      echo $rgCreation   
      echo "##vso[task.setvariable variable=rgCreation;]$rgCreation"
- task: AzureCLI@2
  name: 'CheckVariable'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "$(bicepVersion)"
      echo "$(rgCreation)"